development:
  password: aea8bfb8d567fa251b1efcae3a19ac90
  theme_id: "9723293"
  store: naadz.myshopify.com
  proxy: http://localhost:3000
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - config/settings_data.json

production:
  password: aea8bfb8d567fa251b1efcae3a19ac90
  theme_id: "9723293"
  store: naadz.myshopify.com
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - config/settings_data.json
